"""Add Member model and update Equipment model

Revision ID: 48bb1a0dc3b8
Revises: cfd78fb0ef4f
Create Date: 2024-08-22 04:00:01.591554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bb1a0dc3b8'
down_revision = 'cfd78fb0ef4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'member', ['user_id'], ['id'])
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('user_id')

    op.drop_table('member')
    # ### end Alembic commands ###
