"""Remove image_file column from Equipment model

Revision ID: 92a45e39d3d5
Revises: 8bae1a26fb39
Create Date: 2024-09-02 00:47:50.606924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a45e39d3d5'
down_revision = '8bae1a26fb39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
