"""Reset and add named constraints

Revision ID: c0bcaceda548
Revises: 22c24c39e77e
Create Date: 2024-08-22 04:36:24.592960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bcaceda548'
down_revision = '22c24c39e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_equipment_user', 'member', ['user_id'], ['id'])
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_equipment_user', type_='foreignkey')
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
